# [Federal Data Terminations](https://dataindex.us/terminations-tracker)

Finding rescues of terminated federal datasets. [Jump to the results.](#concise-output)

## Setup

In [1]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path.cwd().parent))

## Load data

### Terminations

In [2]:
import pandas as pd
from helpers import render_links

terminations = pd.read_csv(
    "https://dataindex.us/terminations-tracker/download.csv",
    dtype_backend="pyarrow",
)
render_links(terminations.head())

In [3]:
from analysis.helpers import de_wayback

wayback_archived = terminations[terminations["Primary Link Wayback"].notna()]
primary_urls = de_wayback(wayback_archived["Primary Link Wayback"])

terminations["Primary Link"] = primary_urls

render_links(primary_urls.to_frame())

### Load Data Rescue Project datasets

In [4]:
import httpx

from ptps_wildfire_demo import Resolver

async with httpx.AsyncClient() as client:
    resolver = Resolver(client)

In [5]:
drp_rescues = resolver.drp_rescues

# pull out the rescue URLs
drp_rescues = drp_rescues.assign(
    resource_urls=drp_rescues["resources"].apply(
        lambda resources: ", ".join(
            resource["url"] for resource in resources if resource["url"]
        )
    )
)
drp_rescues = drp_rescues.drop(columns=["resources"])

render_links(drp_rescues.head())

## Fuzzy matches

In [6]:
FDT_URL_FIELDS = [
    "Link 1 URL",
    "Link 2 URL",
    "Link 3 URL",
    "Primary Link",
]

In [7]:
import recordlinkage

MATCH_THRESHOLD = 0.8

indexer = recordlinkage.Index()
indexer.sortedneighbourhood(
    left_on="Dataset Name",
    right_on="title",
    window=5,
)
candidate_pairs = indexer.index(terminations, drp_rescues)

compare = recordlinkage.Compare()
compare.string("Dataset Name", "title", method="jarowinkler", label="title_score")
compare.string("Agency", "agency", method="jarowinkler", label="agency_score")
compare.string(
    "Agency", "organization", method="jarowinkler", label="organization_score"
)

scores: pd.DataFrame = compare.compute(candidate_pairs, terminations, drp_rescues)
scores.index = scores.index.set_names(["termination_index", "rescue_index"])
agency_score = scores[["agency_score", "organization_score"]].max(axis=1)
scores["match_score"] = 0.7 * scores["title_score"] + 0.3 * agency_score

best_matches = (
    scores.sort_values("match_score", ascending=False)
    .groupby(level=0)
    .head(1)
    .query("match_score >= @MATCH_THRESHOLD")
    .reset_index()
)

rescue_matches = best_matches.merge(
    terminations,
    left_on="termination_index",
    right_index=True,
).merge(
    drp_rescues,
    left_on="rescue_index",
    right_index=True,
)


for field in FDT_URL_FIELDS:
    rescue_matches[field] = de_wayback(rescue_matches[field])

columns_to_show = (
    [
        "Dataset Name",
        "Agency",
        "title",
        "agency",
        "organization",
        "title_score",
        "agency_score",
        "match_score",
    ]
    + FDT_URL_FIELDS
    + [
        "url",
        "data_source",
        "resource_urls",
    ]
)

render_links(rescue_matches[columns_to_show])

### Concise output

These are the datasets in the Federal Data Terminations Tracker that have a rescue, per the Data Rescue Project:

In [8]:
render_links(
    rescue_matches[
        [
            "Dataset Name",
            "Agency",
            "url",
        ]
    ].sort_values("Dataset Name")
)