# [Federal Data Terminations](https://dataindex.us/terminations-tracker)

In [1]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path.cwd().parent))

In [2]:
import pandas as pd
from helpers import render_links

terminations = pd.read_csv(
    "https://dataindex.us/terminations-tracker/download.csv",
    dtype_backend="pyarrow",
)
render_links(terminations.head())

In [3]:
terminations["Section"].unique()

<ArrowExtensionArray>
['Datasets Terminated', 'Data Elements Removed']
Length: 2, dtype: string[pyarrow]

In [4]:
wayback_archived = terminations[terminations["Primary Link Wayback"].notna()]
primary_urls = wayback_archived["Primary Link Wayback"].str.replace(
    r"https?://web\.archive\.org/web/\d+/", "", regex=True
)

terminations["Primary Link"] = primary_urls

render_links(primary_urls.to_frame())

In [5]:
import httpx

from ptps_wildfire_demo import Resolver

async with httpx.AsyncClient() as client:
    resolver = Resolver(client)

In [6]:
drp_rescues = resolver.drp_rescues

# pull out the rescue URLs
drp_rescues = drp_rescues.assign(
    resource_urls=drp_rescues["resources"].apply(
        lambda resources: ", ".join(
            resource["url"] for resource in resources if resource["url"]
        )
    )
)
drp_rescues = drp_rescues.drop(columns=["resources"])

render_links(drp_rescues.head())

## Title matches

In [7]:
from rapidfuzz import fuzz, process, utils

MATCH_THRESHOLD = 86
rescue_titles = drp_rescues["title"].dropna()

matches = terminations["Dataset Name"].apply(
    lambda dataset_name: process.extractOne(
        dataset_name,
        rescue_titles,
        scorer=fuzz.WRatio,
        score_cutoff=MATCH_THRESHOLD,
        processor=utils.default_process,
    )
)

matched_terminations = matches.dropna()
title_matches = terminations.loc[
    matched_terminations.index,
    [
        "Dataset Name",
        "Link 1 URL",
        "Link 2 URL",
        "Link 3 URL",
        "Primary Link",
    ],
].copy()
title_matches[["title", "match_score", "rescue_index"]] = pd.DataFrame(
    matched_terminations.tolist(),
    index=matched_terminations.index,
)
title_matches = title_matches.merge(
    drp_rescues[["data_source", "resource_urls"]],
    left_on="rescue_index",
    right_index=True,
    how="left",
)


render_links(
    title_matches[
        [
            "Dataset Name",
            "title",
            "match_score",
            "Link 1 URL",
            "Link 2 URL",
            "Link 3 URL",
            "Primary Link",
            "data_source",
            "resource_urls",
        ]
    ].sort_values("match_score", ascending=False)
)